// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hello.proto

/*
Package hello is a generated protocol buffer package.

It is generated from these files:

	proto/hello.proto
	proto/service.proto

It has these top-level messages:

	StringMessage
	User
*/
package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringMessage struct {
	// required
	Value string   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty" valid:"required"`
	User  *User    `protobuf:"bytes,2,opt,name=User" json:"User,omitempty"`
	Names []string `protobuf:"bytes,3,rep,name=names" json:"names,omitempty"`
}

func (m *StringMessage) Reset()                    { *m = StringMessage{} }
func (m *StringMessage) String() string            { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()               {}
func (*StringMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StringMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StringMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *StringMessage) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type StringMessage_Member struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Age  int64  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *StringMessage_Member) Reset()                    { *m = StringMessage_Member{} }
func (m *StringMessage_Member) String() string            { return proto.CompactTextString(m) }
func (*StringMessage_Member) ProtoMessage()               {}
func (*StringMessage_Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *StringMessage_Member) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StringMessage_Member) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type User struct {
	UserName string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*StringMessage)(nil), "grpcdemo.hello.StringMessage")
	proto.RegisterType((*StringMessage_Member)(nil), "grpcdemo.hello.StringMessage.Member")
	proto.RegisterType((*User)(nil), "grpcdemo.hello.User")
}

func init() { proto.RegisterFile("proto/hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x03, 0xb3, 0x85, 0xf8, 0xd2, 0x8b, 0x0a, 0x92,
	0x53, 0x52, 0x73, 0xf3, 0xf5, 0xc0, 0xa2, 0x4a, 0x53, 0x19, 0xb9, 0x78, 0x83, 0x4b, 0x8a, 0x32,
	0xf3, 0xd2, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73,
	0x4a, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x0d, 0x2e, 0x96, 0xd0,
	0xe2, 0xd4, 0x22, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x11, 0x3d, 0x54, 0x63, 0xf4, 0x40,
	0x72, 0x41, 0x60, 0x15, 0x20, 0xfd, 0x79, 0x89, 0xb9, 0xa9, 0xc5, 0x12, 0xcc, 0x0a, 0xcc, 0x20,
	0xfd, 0x60, 0x8e, 0x94, 0x1e, 0x17, 0x9b, 0x6f, 0x6a, 0x6e, 0x52, 0x6a, 0x91, 0x90, 0x10, 0x17,
	0x8b, 0x5f, 0x62, 0x2e, 0xcc, 0x78, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0x39, 0x31, 0x3d, 0x15, 0x6c,
	0x38, 0x73, 0x10, 0x88, 0xa9, 0xa4, 0x04, 0xb1, 0x4f, 0x48, 0x8a, 0x8b, 0xa3, 0xb4, 0x38, 0xb5,
	0x08, 0x49, 0x07, 0x9c, 0xef, 0xc4, 0x1e, 0xc5, 0x0a, 0xb6, 0x3d, 0x89, 0x0d, 0xec, 0x37, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0x68, 0x69, 0xf3, 0xf0, 0x00, 0x00, 0x00,
}
